import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import './globals.css';
import StoreProvider from './storeProvider';
import { AuthProvider } from '../lib/authContext';
import AuthModal from '../components/AuthModal';
import Sidebar from '../components/Sidebar';
import MainWrapper from '../components/MainWrapper';
import styles from '../app/Sidebar.module.css';
import Navbar from '../components/Navbar';
import { Suspense } from 'react';




const roboto = Roboto({
  weight: ['100', '300', '400', '500', '700', '900'], 
  subsets: ['latin'],
  variable: '--font-roboto',
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"className={roboto.variable}>
     <body>
        <StoreProvider>
          <AuthProvider>
            <AuthModal />
            <div className={styles['app-wrapper']}>
              <Suspense fallback={<div style={{ width: '200px' }} />}>
                <Sidebar />
              </Suspense>
                <MainWrapper>
                 <Navbar/>
                {children}
              </MainWrapper>
            </div>
          </AuthProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
